### ISSUE TITLE
Python2 deprecated

### ISSUE THREAD

**Issue by AndreMerendeira** [IObundle/iob-soc#146]
Python2 is no longer distributed in more recent OS's, so installing the toolchain pre-requisites gives out an error `E: Unable to locate package python2`. In the more recent toolchain versions, python2 has been removed from the pre-requisites installation command. Solution: update Readme file

**Comment by JDLopes** [comment]
> Python2 is no longer distributed in more recent OS's, so installing the toolchain pre-requisites gives out an error `E: Unable to locate package python2`. In the more recent toolchain versions, python2 has been removed from the pre-requisites installation command. Solution: update Readme file

Python2 is not, but Python version 2.7.x still works. You can run 'python --version' in a new Linux installation (at least in Ubuntu variants).

**Comment by AndreMerendeira** [comment]
So, only remove python2 from the pre-requisites install and keep the linkage the same?

**Comment by JDLopes** [comment]
> So, only remove python2 from the pre-requisites install and keep the linkage the same?

I see your point, but since it is part of the riscv-gnu-toolchain installation flow, we should keep it as the authors have on their readme.

**Comment by AndreMerendeira** [comment]
That's the thing, they changed it, no more need for python2

**Comment by JDLopes** [comment]
> That's the thing, they changed it, no more need for python2

So we need to update our readme. I missed that, sorry.

**Comment by P-Miranda** [comment]
I have updated the iob-soc `software/python/` scripts to python3
Is it possible to create a `146-python3` branch so I can PR to upstream and perform Jenkins verification?

**Comment by jjts** [comment]
can I close this one

**Comment by JDLopes** [comment]
> can I close this one

Yes, you can.
