### ISSUE TITLE
create_clock is commented out in sdc

### ISSUE THREAD

**Issue by jjts** [IObundle/iob-soc#174]
if ddr is being used it is not needed as the MIG generates the clocks 

if ddr is not being used the period constraint is missing but it still works 

solution create an if statement so that the statement is valid if ddr not used

**Comment by jjts** [comment]
also in xdc, use an if statement to include it if ddr not present

**Comment by JDLopes** [comment]
This issue can be closed. It has been fixed in pull request #175.
