### ISSUE TITLE
stucks when i simulate with INIT_MEM=0 RUN_EXTMEM=1

### ISSUE THREAD

**Issue by zaliasc** [IObundle/iob-soc#399]
Hello Community,
I try to simulate the iob-soc project with the command (in root directory):
`make sim-run SIMULATOR=icarus INIT_MEM=0 RUN_EXTMEM=1`

but it stucks here:
![image](https://user-images.githubusercontent.com/33146576/168416223-bcd5dff4-820b-44a9-ab3f-0f745b05f8e2.png)

I think this problem has something to do with uart，so i try to debug the python file: software/console/console.
I add some debug message and run it again:
![image](https://user-images.githubusercontent.com/33146576/168416675-9cdc2975-f891-453b-9a0f-bb11d5279768.png)

the result is:
 
![image](https://user-images.githubusercontent.com/33146576/168416326-2dadd7b6-fcb5-4eee-af5f-e17aeba16149.png)

It seems IOB-console script do not receive END flag, and stucks at `tb_read()`
I'm not sure if some dependencies are missing.

Thanks in advance.

distribution:  Ubuntu 18.04

**Comment by jjts** [comment]
Hi @zaliasc, did you make sim-clean before running that? It may have previously compiled objects. Also, note that Icarus is relatively slow, so wait for a little before concluding it is stuck

**Comment by zaliasc** [comment]
Hi @jjts, thanks for your advice.
I will try it later again, but it's not necessary. I just try to use part of the iob-soc project, so i will close the issue.
The project is very informative, thanks again.
