### ISSUE TITLE
can't find iob_uart_swreg_def.vh and iob_uart_swreg.h

### ISSUE THREAD

**Issue by shaoch2001** [IObundle/iob-soc#537]
When I was emulating with vivado, it told me that many macros were not defined. I checked and found that these two header files were missing. I am a beginner and would appreciate your help, thank you!

**Comment by jjts** [comment]
These files are created automatically.

You need to be running Linux, and Vivado is run by 

make fpga-build 

Are you? 

If you are using the GUI you need to find in the makefile tree where these files are generated by the Python script 

./submodules/LIB/scripts/mkregs.py

**Comment by shaoch2001** [comment]
I have find these file by your way. Thank you very much for your reply.
