### ISSUE TITLE
do not update define /if_gen

### ISSUE THREAD

**Issue by jjts** [IObundle/iob-soc#605]
https://github.com/IObundle/iob-soc/blob/f5bbbbc674d9d134cc5a9d9756ae408b3b19777c/iob_soc.py#L351C5-L351C5

check argv before assigning defines

not sure we need update_define() function

**Comment by arturum1** [comment]
This also seems to be resolved in branch if_gen2: https://github.com/IObundle/iob-soc/blob/if_gen2/iob_soc.py#L53

**Comment by jjts** [comment]
Ok but the issue will only b removed if the beach is merged into main
