### ISSUE TITLE
incomprehensible code snippet /if_gen

### ISSUE THREAD

**Issue by jjts** [IObundle/iob-soc#629]
This must go

# Remove [0+:1] part select in AXI connections of ext_mem0 in iob_soc.v template
        if cls.num_extmem_connections == 1:
            inplace_change(
                os.path.join(cls.build_dir, "hardware/src", cls.name + ".v"),
                "[0+:1])",
                ")",
            )

**Comment by jjts** [comment]
stale or done?

**Comment by arturum1** [comment]
Resolved. This snippet was removed in commit https://github.com/IObundle/iob-soc/commit/957b584c0e7ff6333395f128387fef8a6a320733#diff-7c0ac01ecd5af35a96dd499e6888f13b879c4fb981317a5eca7a794945ea6ee1L247-L257.
