### ISSUE TITLE
Repeated source files in VSRC lead to an error

### ISSUE THREAD

**Issue by pedrompt97** [IObundle/iob-soc#69]
When including the peripherals' hardware.mk, repeated source files can be added to VSRC. Currently, there is no way to remove duplicate files, leading to an error:
`Module [MODULE_NAME] was already declared here: ...`

Make has a function that may be useful to solve this issue:
`VSRC:=$(filter-out (FILE_TO_REMOVE),$(VSRC)`

**Comment by jjts** [comment]
repeated submodules are not added. How can repeated files be added ?

**Comment by jjts** [comment]
an example is needed

**Comment by pedrompt97** [comment]
This issue appeared 1 year ago and is no longer valid.
