### ISSUE TITLE
.sdc files for the CSR interfaces should be added to the LIB syn/src folder instead of each core having to repeat them (available and tested in iob-i2s-tdm)

### ISSUE THREAD

**Issue by AndreMerendeira** [IObundle/iob-soc#718]

**Comment by jjts** [comment]
please provide an example. what sdc files?

**Comment by AndreMerendeira** [comment]
The _{CSR_IF}.sdc files used in syn/src are always the same, meaning we just copy-paste them from one project to another. But with the generating of the .sdc files, this issue should go away
