### ISSUE TITLE
create_wrapper_files

### ISSUE THREAD

**Issue by jjts** [IObundle/iob-soc#759]
What wrapper what files? Isn't there a better name?

cyclonev related scripts should go to the cyclonev directory

do not shebang files that do not run standalone and do not give them x permission (fixed)

**Comment by jjts** [comment]
Add a header comment explaining what the files does

**Comment by arturum1** [comment]
For now, every iob-soc python script (except for the main iob_soc.py) is located in the `scripts/` directory.
Should I create new scripts in each of the boards/simulation directories with functions dedicated for them?

**Comment by jjts** [comment]
yes, please

each board, simulator, etc has its own folder 

except synthesis as for now we only use one tool

**Comment by jjts** [comment]
some  files belong to the FPGA compile tool, not to any specific board

**Comment by arturum1** [comment]
Removed create_wrapper_files script in commit https://github.com/IObundle/iob-soc/pull/906/commits/834f533cad7e97e739bd43204514116c24f95cff.
Currenlty, in if_gen2, fpga and simulation wrappers are generated with py2hwsw.
