### ISSUE TITLE
deprecate the flows variable

### ISSUE THREAD

**Issue by jjts** [IObundle/iob-soc#765]

**Comment by arturum1** [comment]
I think this was already resolved in https://github.com/IObundle/iob-soc/pull/651

**Comment by arturum1** [comment]
Those functions can just be renamed. The 'flow' keyword is just a way for us to distinguish between the different build processes, like 'simulation', 'fpga', 'syn', 'lint', 'sw', ...
What should we name these processes/functions if not 'flows'?

For example, what should the name of the `flows_setup` function be? Maybe `setup_build_processes`?

**Comment by arturum1** [comment]
This can be deleted as it is unused:
`submodules/LIB/hardware/modules/iob_timer/iob_timer.py: flows = "sim emb"`
