### ISSUE TITLE
should be iob_interface like the others

### ISSUE THREAD

**Issue by jjts** [IObundle/iob-soc#804]
https://github.com/IObundle/iob-soc/blob/cd83a441a2acf143f21e3c9c471b74e1a729f4a9/iob_soc.py#L183

**Comment by jjts** [comment]
this seems done or dated

**Comment by arturum1** [comment]
No longer applicable.
Interfaces are now defined using the [interface](https://github.com/IObundle/iob-soc/blob/if_gen2/iob_soc.py#L171-L174) attribute of the wires/ports.
