### ISSUE TITLE
range in single bit signals

### ISSUE THREAD

**Issue by jjts** [IObundle/iob-soc#850]
On branch ifgen2 single bit wires and ports are being declared with [1-1:0] and no should be given in these cases

**Comment by arturum1** [comment]
Resolved in commit https://github.com/IObundle/py2hwsw/commit/211b8f9c72463da6199604c8ac7777978c4abe1b#diff-0afc8cedf02f65f3eef55a85f3350dbe5a1ee9933749f5ae2ac0b077828dd235R37
