### ISSUE TITLE
Possible wrong `nix` dependencies path configuration.

### ISSUE THREAD

**Issue by roby2014** [IObundle/iob-soc#924]
Hello. I was trying to use the nix environment, however, I've encountered a weird behaviour (I think)

## Reproduce
```sh
➜  repos git clone git@github.com:IObundle/iob-soc.git --recursive     
[...]                                    
➜  iob-soc git:(main) make setup
nix-shell --run 'make build-setup SETUP_ARGS="LIB_DIR=submodules/LIB INIT_MEM"'
error:
       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:34:12:
           33|
           34|   strict = derivationStrict drvAttrs;
             |            ^
           35|

       … while evaluating derivation 'iob-shell'
         whose name attribute is located at /nix/store/fvsb3dkbqwn2q01llw1dsfp35hq7wdxg-nixos-22.11/pkgs/stdenv/generic/make-derivation.nix:270:7

       … while evaluating attribute 'buildInputs' of derivation 'iob-shell'
         at /nix/store/fvsb3dkbqwn2q01llw1dsfp35hq7wdxg-nixos-22.11/pkgs/stdenv/generic/make-derivation.nix:314:7:
          313|       depsHostHost                = lib.elemAt (lib.elemAt dependencies 1) 0;
          314|       buildInputs                 = lib.elemAt (lib.elemAt dependencies 1) 1;
             |       ^
          315|       depsTargetTarget            = lib.elemAt (lib.elemAt dependencies 2) 0;

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: path '/home/roby/repos/iob-soc/riscv-gnu-toolchain.nix' does not exist
make: *** [Makefile:24: setup] Error 1
```

## Cause 

This is caused by `default.nix` yosys and risc-v toolchain configuration [here](https://github.com/IObundle/iob-soc/blob/main/submodules/LIB/scripts/default.nix#L31).
When executing `make setup`, my nix-shell is looking for `riscv-gnu-toolchain.nix` and `yosys.nix` in the root path.

## Possible fix

May I ask why are you using symlinks for `default.nix`? Shouldnt a root one be enough and to import others?

Changing to its absolute path: e.g `(callPackage ./submodules/LIB/scripts/riscv-gnu-toolchain.nix { })` and `yosys = import ./submodules/LIB/scripts/yosys.nix { inherit pkgs; };` worked.

LMK if this fix is ok, so I can open a PR if needed.

## System
I'm also confused why it works on your CI but not on my system, but I can investigate further if needed.

Branch: `master`
Nix-shell version: `nix-shell (Nix) 2.24.3`

**Comment by arturum1** [comment]
Hi, thank you for opening this issue.
I updated the nix-shell version on my machine and was able to reproduce the error.

It looks like new versions of nix-shell treat symlinks differently from old ones.
Our CI machines use Nix-shell version: `nix-shell (Nix) 2.18.4`. This is probably why the error did not appear sooner.

PR https://github.com/IObundle/iob-soc/pull/925 should fix this issue by replacing symlinks with Nix imports.
