### ISSUE TITLE
iob_reset_sync should be called iob_areset_sync

### ISSUE THREAD

**Issue by AndreMerendeira** [IObundle/iob-soc#942]
This change should be made in order to avoid erroneous usage

**Comment by jjts** [comment]
in which branch and module?

**Comment by jjts** [comment]
without more info, delete this issue

**Comment by jjts** [comment]
ok, it is a module .

sync reset do not need to be synced. What erroneous usage then?

**Comment by AndreMerendeira** [comment]
one can think this should be used to sync synchronous resets, but in fact it should be used to sync the Asynchronous resets
