### ISSUE TITLE
clang format 

### ISSUE THREAD

**Issue by jjts** [IObundle/iob-soc#947]
why do we have that at the root? can it go to py2?

**Comment by P-Miranda** [comment]
Usually the `.clang-format` file is in the directory from where the `clang-format` command is called.
But is also possible to use a `.clang-format` from other path with the command:
```
clang-format --style=file:./path/to/config/.clang-format -i <files-to-format>
```
We can add the `.clang-format` file to py2 and update the `clang-format` command executed in `py2hwsw/scripts/sw_tools.py` accordingly.

This will remove the need to have a `.clang-format` at the root of every repository, 
but also the possibility to have different format styles for each project (which I don't think we need for now).
