### ISSUE TITLE
Support multiple clocks for Verilator Simulation

### ISSUE THREAD

**Issue by P-Miranda** [IObundle/iob-soc#949]
Verilator simulation toggles clocks from function `Timer()` in `iob_tasks.cpp` and only supports a single hardcoded `clk`.
- Update `iob_tasks.cpp` to support multiple clocks 
- or add pointer to custom `Timer()` function that can be implemented in `iob_soc_tb.cpp` or equivalent top level testbench for verilator.

This applies to all branches and relates to `.cpp` files that are not directly affected by `if_gen2` developments.

**Comment by jjts** [comment]
We have tried this before; isn't there a timing directive that causes issues?
